### ISSUE TITLE
Use PHImageRequestOptionsDeliveryModeHighQualityFormat instead of PHImageRequestOptionsDeliveryModeFastFormat

### ISSUE THREAD

**Issue by fdecampredon** [idrisssakhi/photoGallery#2]
At this line https://github.com/idrisssakhi/photoGallery/blob/main/ios/RNPhotoGallery.m#L516  you use PHImageRequestOptionsDeliveryModeFastFormat which result in very low quality jpeg, using PHImageRequestOptionsDeliveryModeHighQualityFormat or allowing to customize the quality could make the jpeg conversion easier.

**Comment by idrisssakhi** [comment]
@fdecampredon the issue is resolved, please check new version 1.2.0

**Comment by fdecampredon** [comment]
Thanks
