### ISSUE TITLE
Build Failed Android - Execution failed for task ':react-native-photo-gallery-api:compileDebugJavaWithJavac'.

### ISSUE THREAD

**Issue by TeeRa0ne** [idrisssakhi/photoGallery#4]
Hi,

When i build my app this error spawn.

<img width="1104" alt="Capture d’écran 2022-07-08 à 10 53 31" src="https://user-images.githubusercontent.com/60188443/177965218-6cb45cd6-c0cb-4b0b-b6bd-326ec02084bb.png">

If you have a solution for this ?

**Comment by idrissakhi** [comment]
Hey 👋 , you need to use JAVA 8 or more to build app, otherwise lambda expressions are not known. you can check your actual java version.

**Comment by TeeRa0ne** [comment]
Thanks you for you're reply.
I am already on version 8 of JAVA.

**Comment by idrissakhi** [comment]
Can you send me the reproduction steps, and also the command line you are using please

**Comment by TeeRa0ne** [comment]
**Reproduction Steps :**

- Add into app/build.gradle : `compile project(':react-native-photo-gallery-api')` in dependencies group
- Add into settings.gradle : 
```
include ':react-native-photo-gallery-api'
project(':react-native-photo-gallery-api').projectDir = new File(rootProject.projectDir, 	'../node_modules/react-native-photo-gallery-api/android')
```

**Command line :**
`npm run android`

**Comment by idrissakhi** [comment]
yarn add
yarn install then you sync your android project on android studio and you start the app

**Comment by TeeRa0ne** [comment]
My version of React Native is 0.64.2

And with yarn is the same erorr

**Comment by TeeRa0ne** [comment]
Incredible thanks you, i will test this version today

**Comment by TeeRa0ne** [comment]
It's work thanks you !

**Comment by idrisssakhi** [comment]
Don't hesitate to leave a STAR on the repo, 😉😅
