### ISSUE TITLE
 photoLibraryPermissionModule: Native Module 'photoLibraryPermissionModule' was null! Did you run pod install?

### ISSUE THREAD

**Issue by EmanueleAgo** [idrisssakhi/photoGallery#6]
Hello, I am trying use this library to save some images but I have this error (with android development, not ios): 
` photoLibraryPermissionModule: Native Module 'photoLibraryPermissionModule' was null! Did you run pod install?`

This is my code:

```
import {PhotoGallery} from 'react-native-photo-gallery-api'

async function hasAndroidPermission() {
  const permission = PermissionsAndroid.PERMISSIONS.WRITE_EXTERNAL_STORAGE;

  const hasPermission = await PermissionsAndroid.check(permission);
  if (hasPermission) {
    return true;
  }

  const status = await PermissionsAndroid.request(permission);
  return status === 'granted';
}
const savePicture = async (path)=>{
  if (Platform.OS === "android" && !(await hasAndroidPermission())) {
    return;
  }
  PhotoGallery.saveToCameraRoll(path, { type:'photo', album:'Album' })
}
```

The image is saved and the album was created, but I have the error when I call savePicture.
This are the step that I followed to install the package:
- run `yarn add react-native-photo-gallery-api`
- add in `android/settings.gradle:`
 ```
include ':react-native-photo-gallery'
project(':react-native-photo-gallery').projectDir = new File(rootProject.projectDir, 	'../node_modules/react-native-photo-gallery/android')
```
- run in `android `folder: `./gradlew clean`

How can I fix it?
 Thanks in advance for a possible reply.

**Comment by EmanueleAgo** [comment]
`"react-native": "0.68.2"`
 I know that linking is automatic from 0.60. I also try to install this package using `npm install react-native-photo-gallery-api --save` insted of  `yarn add react-native-photo-gallery-api` but I have same error.

**Comment by EmanueleAgo** [comment]
There are updates?

**Comment by idrisssakhi** [comment]
yes, would you check the version 1.2.2 please and keep me updated

**Comment by EmanueleAgo** [comment]
Very very thanks! Now it works perfectly :)
